# Generated by Django 4.2.6 on 2023-12-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schoolrecord',
            fields=[
                ('uname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('slocation', models.CharField(max_length=30)),
                ('sprincipal', models.CharField(max_length=30)),
            ],
        ),
    ]
