# Generated by Django 4.2.6 on 2024-01-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schoolrecord',
            new_name='schooldata',
        ),
    ]
